name: Summarize new issues

on:
  issues:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create summary comment
        run: |
          echo "创建问题摘要..."
          echo "问题标题：${{ github.event.issue.title }}"
          echo "问题正文：${{ github.event.issue.body }}"
          # 由于 actions/ai-inference@v1 可能不存在，这里使用简单的摘要逻辑
          SUMMARY="问题摘要：${{ github.event.issue.title }} - 由 ${{ github.event.issue.user.login }} 创建"
          echo "摘要：$SUMMARY"
          echo "SUMMARY=$SUMMARY" >> $GITHUB_ENV

      - name: Comment with summary
        run: |
          gh issue comment $ISSUE_NUMBER --body '$SUMMARY'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          SUMMARY: ${{ env.SUMMARY }}

# 可用的 Action 库（已去重）
# 缓存 Action
# - name: 缓存
#   uses: actions/cache@v5.0.2
#   with:
#     # 要缓存和恢复的文件、目录和通配符模式的列表
#     path:
#     # 用于恢复和保存缓存的显式密钥
#     key:
#     # 列出前缀匹配键的有序多行字符串，如果键没有发生缓存命中，则用于恢复过时的缓存
#     restore-keys: # 可选
#     # 上传时用于分割大文件的块大小，以字节为单位
#     upload-chunk-size: # 可选
#     # 启用时可选的布尔值，允许 Windows 运行程序保存或恢复可以在其他平台上分别恢复或保存的缓存
#     enableCrossOsArchive: # 可选，默认为 false
#     # 如果未找到缓存条目，则工作流程失败
#     fail-on-cache-miss: # 可选，默认为 false
#     # 检查给定输入（key、restore-keys）是否存在缓存条目，而不下载缓存
#     lookup-only: # 可选，默认为 false
#     # 运行后步骤以保存缓存，即使之前的另一个步骤失败
#     save-always: # 可选，默认为 false

# 设置 Go 环境
# - name: 设置 Go 环境
#   uses: actions/setup-go@v6.2.0
#   with:
#     # 要下载（如果需要）和使用的 Go 版本。支持 semver 规范和范围
#     go-version: # 可选
#     # go.mod、go.work、.go-version 或 .tool-versions 文件的路径
#     go-version-file: # 可选
#     # 如果您希望操作始终检查满足版本规范的最新可用版本，请将此选项设置为 true
#     check-latest: # 可选
#     # 用于从 go-versions 中提取 Go 发行版的令牌
#     token: # 可选，默认为 ${{ github.server_url == 'https://github.com' && github.token || '' }}
#     # 用于指定是否需要缓存
#     cache: # 可选，默认为 true
#     # 用于指定依赖文件的路径 - go.sum
#     cache-dependency-path: # 可选
#     # Go 使用的目标架构
#     architecture: # 可选

# 创建工件 YAML
# - name: 创建工件 YAML
#   uses: opencontextinc/create-artifact-yaml@v1.0.1
#   with:
#     # 工件的类型。 sbom、容器、包或映像之一
#     type:
#     # 工件的 URL/URI
#     url:
#     # 保存 YAML 文件的目录
#     directory: # 可选

# 创建部署请求
# - name: 创建部署请求
#   uses: planetscale/create-deploy-request-action@v2
#   with:
#     # 数据库的名称
#     database-name:
#     # 新分支的名称
#     branch-name:
#     # 拥有数据库的组织的名称
#     organization-name:
#     # 将更改合并到的目标分支
#     deploy-to: # 可选，默认为 main

# Accurics GitHub Action
# - name: Accurics GitHub Action
#   uses: tenable/accurics-action@v2.0.3
#   with:
#     # 调试模式
#     debug-mode: # 可选
#     # 用于处理此存储库中的文件的 Terraform 版本
#     terraform-version: # 可选，默认为最新
#     # 要在此存储库中扫描的目录列表，以空格分隔
#     directory: # 可选，默认为 .
#     # Terraform 计划参数
#     plan-args: # 可选
#     # Accurics 扫描的环境 ID
#     env-id: # 可选
#     # Accurics CLI 应用程序令牌 ID
#     app-id: # 可选
#     # 存储库位置
#     repo: # 可选，默认为 __empty__
#     # Accurics 应用程序 URL
#     url: # 可选，默认为 https://cloud.tenable.com/cns
#     # 允许 Accurics 在发现违规时使构建失败
#     fail-on-violations: # 可选，默认为 true
#     # 允许 Accurics 在遇到任何错误时使构建失败
#     fail-on-all-errors: # 可选，默认为 true
#     # 允许 Accurics 切换到基于 terrascan 的分析
#     scan-mode: # 可选，默认为 plan
#     # 允许 Accurics 将数据放入 tenable.cs Web 控制台中的管道选项卡
#     pipeline: # 可选

# PolyAPI 部署操作 (Python)
# - name: PolyAPI 部署操作 (Python)
#   uses: polyapi/poly-deployment-action-py@v0.0.8
#   with:
#     # Poly 的 API 密钥
#     poly_api_key:
#     # 部署目标 Poly 实例的基本 URL
#     poly_api_base_url:
#     # 操作是否应该运行自己的 actions/checkout 步骤
#     do_checkout: # 可选，默认为 true
#     # 运行 Poly 命令的路径
#     working_directory: # 可选，默认为 .

# Python Black
# - name: Python Black
#   uses: cytopia/docker-black@0.11
#   with:
#     # 要检查的路径（默认为当前目录）
#     path: # 可选，默认为 ./

# Python 语义发布 - 发布
# - name: Python 语义发布 - 发布
#   uses: python-semantic-release/publish-action@v10.5.3
#   with:
#     # 自定义语义发布配置文件的路径
#     config_file: # 可选，默认为
#     # 在运行语义发布发布之前要更改为的子目录
#     directory: # 可选，默认为 .
#     # 用于上传工件的 GitHub 令牌
#     github_token:
#     # 如果设置为 true，github 操作将传递 --noop 参数
#     no_operation_mode: # 可选，默认为 false
#     # 与工件应该发布到的 GitHub Release 相对应的标签
#     tag: # 可选，默认为最新
#     # 将输出的详细级别设置为要传递给的 -v 的数量
#     verbosity: # 可选，默认为 1

# 安装 .NET Core SDK
# - name: 安装 .NET Core SDK
#   uses: actions/setup-dotnet@v5.1.0
#   with:
#     # 要使用的可选 SDK 版本
#     dotnet-version: # 可选
#     # 可选的构建质量
#     dotnet-quality: # 可选
#     # 可选的 global.json 位置
#     global-json-file: # 可选
#     # 为其设置身份验证的可选包源
#     source-url: # 可选
#     # 可选所有者
#     owner: # 可选
#     # 可选的 NuGet.config 位置
#     config-file: # 可选
#     # 启用 NuGet 全局包文件夹缓存的可选输入
#     cache: # 可选
#     # 用于指定依赖文件的路径：packages.lock.json
#     cache-dependency-path: # 可选

# 安装 CD 工具
# - name: 安装 CD 工具
#   uses: daisaru11/setup-cd-tools@v1.0.0
#   with:
#     # 安装 jq
#     jq: # 可选
#     # 安装 yq
#     yq: # 可选
#     # 安装 kubectl
#     kubectl: # 可选
#     # 安装自定义工具
#     custom: # 可选
#     # 安装 helm
#     helm: # 可选
#     # 安装 hub
#     hub: # 可选

# 设置 Node.js 环境
# - name: 设置 Node.js 环境
#   uses: actions/setup-node@v6.2.0
#   with:
#     # 要使用的版本的版本规范
#     node-version: # 可选
#     # 包含要使用的版本的版本规范的文件
#     node-version-file: # 可选
#     # Node 使用的目标架构
#     architecture: # 可选
#     # 如果您希望操作检查满足版本规范的最新可用版本，请设置此选项
#     check-latest: # 可选
#     # 用于设置身份验证的可选注册表
#     registry-url: # 可选
#     # 针对范围注册表进行身份验证的可选范围
#     scope: # 可选
#     # 用于从节点版本中提取节点发行版的令牌
#     token: # 可选，默认为 ${{ github.server_url == 'https://github.com' && github.token || '' }}
#     # 用于指定一个包管理器在默认目录中进行缓存
#     cache: # 可选
#     # 设置为 false 以禁用自动缓存
#     package-manager-cache: # 可选，默认为 true
#     # 用于指定依赖文件的路径
#     cache-dependency-path: # 可选
#     # 用于指定一个替代镜像来下载 Node.js 二进制文件
#     mirror: # 可选
#     # 从镜像获取时用作授权标头的令牌
#     mirror-token: # 可选