name: Unified Terminal Configuration

on:
  workflow_dispatch:
    inputs:
      terminal_type:
        description: 'Terminal type'
        required: true
        default: 'powershell'
        type: choice
        options:
          - powershell
          - nodejs
          - both
      test_type:
        description: 'Test type'
        required: true
        default: 'basic'
        type: choice
        options:
          - basic
          - advanced
          - security

jobs:
  unified-terminal-test:
    name: Unified Terminal Test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        if: github.event.inputs.terminal_type == 'nodejs' || github.event.inputs.terminal_type == 'both'
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: PowerShell Terminal Test
        if: github.event.inputs.terminal_type == 'powershell' || github.event.inputs.terminal_type == 'both'
        shell: powershell
        run: |
          Write-Host "=== PowerShell Terminal Test ==="
          Write-Host "Terminal Type: ${{ github.event.inputs.terminal_type }}"
          Write-Host "Test Type: ${{ github.event.inputs.test_type }}"
          Write-Host "Timestamp: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")"
          
          # è®¾ç½®æ‰§è¡Œç­–ç•¥
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
          
          # æ˜¾ç¤º PowerShell ç‰ˆæœ¬
          Write-Host "PowerShell Version: $($PSVersionTable.PSVersion.ToString())"
          
          # åˆ›å»º PowerShell é…ç½®æ–‡ä»¶
          $profileDir = Split-Path -Parent $PROFILE
          if (!(Test-Path $profileDir)) {
              New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
          }
          
          $profileContent = @"
          # Unified PowerShell Profile
          
          # å¸¸ç”¨åˆ«å
          New-Alias -Name ll -Value Get-ChildItem
          New-Alias -Name ls -Value Get-ChildItem
          
          # å¸¸ç”¨å‡½æ•°
          function Get-FileSize {
              param(
                  [string]$Path = "."
              )
              Get-ChildItem -Path $Path | Select-Object Name, Length, LastWriteTime
          }
          
          # è‡ªå®šä¹‰æç¤ºç¬¦
          function prompt {
              "PS $($PWD.Path) > "
          }
          "@
          
          $profileContent | Out-File -FilePath $PROFILE -Force -Encoding UTF8
          . $PROFILE
          
          # åŸºæœ¬å‘½ä»¤æµ‹è¯•
          if ('${{ github.event.inputs.test_type }}' -eq 'basic' -or '${{ github.event.inputs.test_type }}' -eq 'advanced') {
              Write-Host "\n=== Basic PowerShell Commands ==="
              Get-ChildItem
              Get-Location
              New-Item -ItemType Directory -Path "test-dir" -Force
              "Hello from PowerShell!" | Out-File -FilePath "test-dir\test.txt" -Force
              Get-Content -Path "test-dir\test.txt"
              Remove-Item -Path "test-dir" -Recurse -Force
              Write-Host "âœ?PowerShell basic commands executed successfully"
          }
          
          # é«˜çº§å‘½ä»¤æµ‹è¯•
          if ('${{ github.event.inputs.test_type }}' -eq 'advanced') {
              Write-Host "\n=== Advanced PowerShell Commands ==="
              Get-ChildItem | Where-Object {$_.Extension -eq ".yml" -or $_.Extension -eq ".yaml"} | Select-Object Name, Length
              try {
                  Get-Item -Path "non-existent-file.txt"
              } catch {
                  Write-Host "Error caught: $($_.Exception.Message)"
              }
              function Get-SystemInfo {
                  param([string]$ComputerName = "localhost")
                  Write-Host "System info for $ComputerName"
                  Write-Host "OS: $($env:OS)"
                  Write-Host "Processor: $($env:PROCESSOR_IDENTIFIER)"
              }
              Get-SystemInfo
              Write-Host "âœ?PowerShell advanced commands executed successfully"
          }
          
          # å®‰å…¨å‘½ä»¤æµ‹è¯•
          if ('${{ github.event.inputs.test_type }}' -eq 'security') {
              Write-Host "\n=== Security PowerShell Commands ==="
              Get-ExecutionPolicy -List
              Get-Module -ListAvailable | Select-Object Name, Version | Select-Object -First 5
              Get-ChildItem -Path Env: | Where-Object {$_.Name -like "*TOKEN*" -or $_.Name -like "*SECRET*"} | ForEach-Object {
                  Write-Host "Found sensitive environment variable: $($_.Name)"
              }
              Write-Host "âœ?PowerShell security commands executed successfully"
          }

      - name: Node.js Terminal Test
        if: github.event.inputs.terminal_type == 'nodejs' || github.event.inputs.terminal_type == 'both'
        shell: cmd
        run: |
          echo === Node.js Terminal Test ===
          echo Terminal Type: ${{ github.event.inputs.terminal_type }}
          echo Test Type: ${{ github.event.inputs.test_type }}
          echo Timestamp: %DATE% %TIME%
          
          :: è®¾ç½®çŽ¯å¢ƒå˜é‡
          echo NODE_ENV=development >> %GITHUB_ENV%
          echo NPM_CONFIG_PREFIX=%USERPROFILE%\.npm-global >> %GITHUB_ENV%
          echo PATH=%PATH%;%USERPROFILE%\.npm-global\bin >> %GITHUB_ENV%
          
          :: å®‰è£…å…¨å±€åŒ?          npm install -g npm@latest
          npm install -g yarn
          npm install -g pnpm
          npm install -g typescript
          npm install -g eslint
          npm install -g prettier
          
          :: åŸºæœ¬å‘½ä»¤æµ‹è¯•
          if "${{ github.event.inputs.test_type }}" == "basic" || "${{ github.event.inputs.test_type }}" == "advanced" (
              echo "\n=== Basic Node.js Commands ==="
              node --version
              npm --version
              yarn --version
              pnpm --version
              npm list -g --depth=0
              
              :: åˆ›å»ºæµ‹è¯•é¡¹ç›®
              echo {
              echo   "name": "test-project",
              echo   "version": "1.0.0",
              echo   "description": "Test project",
              echo   "main": "index.js",
              echo   "scripts": {
              echo     "test": "echo \"Error: no test specified\" && exit 1"
              echo   },
              echo   "keywords": [],
              echo   "author": "",
              echo   "license": "MIT"
              echo } > package.json
              
              dir
              echo âœ?Node.js basic commands executed successfully
          )
          
          :: é«˜çº§å‘½ä»¤æµ‹è¯•
          if "${{ github.event.inputs.test_type }}" == "advanced" (
              echo "\n=== Advanced Node.js Commands ==="
              
              :: åˆ›å»ºå’Œè¿è¡Œç®€å•åº”ç”?              echo console.log('Hello from Node.js!'); > index.js
              node index.js
              
              :: å®‰è£…ä¾èµ–
              npm install express
              
              :: åˆ›å»º Express åº”ç”¨
              echo const express = require('express'); > app.js
              echo const app = express(); >> app.js
              echo const port = 3000; >> app.js
              echo >> app.js
              echo app.get('/', (req, res) => { >> app.js
              echo   res.send('Hello World!'); >> app.js
              echo }); >> app.js
              echo >> app.js
              echo app.listen(port, () => { >> app.js
              echo   console.log(`Example app listening on port ${port}`); >> app.js
              echo }); >> app.js
              
              dir
              type package.json
              echo âœ?Node.js advanced commands executed successfully
          )
          
          :: å®‰å…¨å‘½ä»¤æµ‹è¯•
          if "${{ github.event.inputs.test_type }}" == "security" (
              echo "\n=== Security Node.js Commands ==="
              npm audit
              npm config list
              set NODE
              findstr /i "token secret password api_key" package.json || echo No sensitive information found in package.json
              echo âœ?Node.js security commands executed successfully
          )

      - name: Generate Unified Terminal Report
        shell: powershell
        run: |
          Write-Host "=== Unified Terminal Report ==="
          
          $reportContent = @"
          # Unified Terminal Test Report
          
          ## Test Information
          - Terminal Type: ${{ github.event.inputs.terminal_type }}
          - Test Type: ${{ github.event.inputs.test_type }}
          - Timestamp: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
          - Runner OS: $env:RUNNER_OS
          - PowerShell Version: $($PSVersionTable.PSVersion.ToString())
          - Node.js Version: $(node --version 2>$null || echo "Not tested")
          - npm Version: $(npm --version 2>$null || echo "Not tested")
          
          ## Test Results
          - âœ?Unified terminal environment set up
          - âœ?Terminal commands executed
          - âœ?Terminal configuration validated
          
          ## System Information
          - Computer Name: $env:COMPUTERNAME
          - User Name: $env:USERNAME
          - Working Directory: $(Get-Location)
          - Environment Variables Count: $(Get-ChildItem -Path Env: | Measure-Object).Count
          "@
          
          $reportPath = ".github/actions-config/logs/unified-terminal-report-$(Get-Date -Format "yyyyMMdd_HHmmss").md"
          $reportDir = Split-Path -Parent $reportPath
          if (!(Test-Path $reportDir)) {
              New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
          }
          
          $reportContent | Out-File -FilePath $reportPath -Force -Encoding UTF8
          
          Write-Host "âœ?Unified terminal report generated: $reportPath"

      - name: Upload Unified Terminal Report
        uses: actions/upload-artifact@v4
        with:
          name: unified-terminal-report
          path: .github/actions-config/logs/unified-terminal-report-*.md\n
