allowed_sources:
  - actions/checkout
  - actions/setup-node
  - actions/setup-python
  - peaceiris/actions-gh-pages
  - actions/upload-artifact

installed_actions:
  - name: actions/checkout
    version: v4
    source: actions/checkout
    usage: 每天使用
    security: 已审核
    workflows: [ci-cd.yml, deploy.yml]
  
  - name: actions/setup-node
    version: v5
    source: actions/setup-node
    usage: 每周使用
    security: 已审核
    workflows: [deploy.yml]
  
  - name: actions/setup-python
    version: v5
    source: actions/setup-python
    usage: 每月使用
    security: 已审核
    workflows: [security-scan.yml]
  
  - name: peaceiris/actions-gh-pages
    version: v4
    source: peaceiris/actions-gh-pages
    usage: 每季度使用
    security: 已审核
    workflows: [deploy.yml]
  
  - name: actions/upload-artifact
    version: v4
    source: actions/upload-artifact
    usage: 每年使用
    security: 已审核
    workflows: [security-scan.yml]

custom_actions:
  - name: my-custom-action
    version: v1
    source: my-org/my-repo
    usage: 测试使用
    security: 待审核
    workflows: [test.yml]