# GitHubå¸‚åœºå®‰è£…ç¨‹åºé›†ä¸­ç®¡ç†é…ç½®æ–‡ä»¶
# ç”¨äºç®¡ç†ä»GitHubå¸‚åœºå®‰è£…çš„æ‰€æœ‰Action

# å…è®¸çš„Actionæ¥æºåˆ—è¡¨
allowed_sources:
  - actions/checkout
  - actions/setup-node
  - actions/setup-python
  - peaceiris/actions-gh-pages
  - actions/upload-artifact
  - actions/cache
  - actions/download-artifact
  - actions/upload-release-asset
  - actions/create-release
  - actions/labeler
  - actions/stale
  - actions/delete-package-versions
  - actions/setup-go
  - actions/setup-java
  - actions/setup-dotnet
  - actions/setup-ruby
  - actions/setup-php
  - actions/setup-node
  - actions/setup-python
  - actions/setup-ruby
  - actions/setup-dotnet
  - actions/setup-java
  - actions/setup-go
  - actions/setup-php
  - actions/setup-ruby
  - actions/setup-dotnet
  - actions/setup-java
  - actions/setup-go
  - actions/setup-php

# å·²å®‰è£…çš„Actioné…ç½®
installed_actions:
  - name: actions/checkout
    version: v4
    source: actions/checkout
    usage: æ¯å¤©ä½¿ç”¨
    security: å·²å®¡æ ?    workflows: [ci-cd.yml, deploy.yml]
    description: æ£€å‡ºä»“åº“ä»£ç ?  
  - name: actions/setup-node
    version: v5
    source: actions/setup-node
    usage: æ¯å‘¨ä½¿ç”¨
    security: å·²å®¡æ ?    workflows: [deploy.yml]
    description: è®¾ç½®Node.jsç¯å¢ƒ
  
  - name: actions/setup-python
    version: v5
    source: actions/setup-python
    usage: æ¯æœˆä½¿ç”¨
    security: å·²å®¡æ ?    workflows: [security-scan.yml]
    description: è®¾ç½®Pythonç¯å¢ƒ
  
  - name: peaceiris/actions-gh-pages
    version: v4
    source: peaceiris/actions-gh-pages
    usage: æ¯å­£åº¦ä½¿ç”?    security: å·²å®¡æ ?    workflows: [deploy.yml]
    description: éƒ¨ç½²åˆ°GitHub Pages
  
  - name: actions/upload-artifact
    version: v4
    source: actions/upload-artifact
    usage: æ¯å¹´ä½¿ç”¨
    security: å·²å®¡æ ?    workflows: [security-scan.yml]
    description: ä¸Šä¼ æ„å»ºäº§ç‰©

# è‡ªå®šä¹‰Actioné…ç½®
custom_actions:
  - name: my-custom-action
    version: v1
    source: my-org/my-repo
    usage: æµ‹è¯•ä½¿ç”¨
    security: å¾…å®¡æ ?    workflows: [test.yml]
    description: è‡ªå®šä¹‰Action\n
